// demo/next-demo/pages/index.tsx
import { Counter, Joke, PrimaryButton, TestPage, TextBlock, LinkButton } from '@demo/ui-kit';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useCallback } from 'react';
import { contentPageContext } from '../contentPageContext/contentPageContext';

const Home: NextPage = () => {
  const primary = 'Айзек Азимов';
  const secondary = [
    'Нельзя сказать человеку: «Ты можешь творить.',
    'Так давай, твори». Гораздо вернее подождать, пока он',
    'сам не скажет: «Я могу творить, и я буду творить, хотите',
    'вы этого или нет».'
  ];

  const debugEvent = useCallback((_: unknown) => {
    console.log(_);
  }, []);

  return (
    <>
      <Head>
        <title>Demo of unified JSX for Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Next.js with unified components</h1>
      <hr />
      <TextBlock primary={primary} secondary={secondary} dark onCite={debugEvent}>
        <cite>http://www.asimovonline.com</cite>
      </TextBlock>
      <PrimaryButton onClick={debugEvent}>Click me</PrimaryButton>
      <hr />
      <Counter context={contentPageContext} />
      <hr />
      <Joke context={contentPageContext} />
      <hr />
      <LinkButton context={contentPageContext}>To test page</LinkButton>
      <hr />
      <TestPage />
    </>
  );
};

export default Home;

// demo/nuxt-demo/pages/index.vue
<template>
  <div>
    <h1>Nuxt with unified components</h1>
    <hr />
    <text-block ref="text" :primary="primary" :secondary="secondary" :dark="true" @cite="debugEvent">
      <cite>http://www.asimovonline.com</cite>
    </text-block>
    <primary-button @click="debugEvent">Click me</primary-button>
    <hr />
    <counter :context="contentPageContext" />
    <hr />
    <joke :context="contentPageContext" />
    <hr />
    <link-button :context="contentPageContext">To test page</link-button>
    <hr />
    <test-page />
  </div>
</template>

<script lang="ts">
import { Counter, Joke, LinkButton, PrimaryButton, TestPage, TextBlock } from '@demo/ui-kit';
import { defineComponent } from 'vue';
import { contentPageContext } from '../contentPageContext/contentPageContext';

export default defineComponent({
  name: 'App',
  components: {
    TestPage,
    TextBlock,
    PrimaryButton,
    Counter,
    Joke,
    LinkButton,
  },
  mounted() {
    console.log(this.$refs.text);
  },
  data() {
    return {
      contentPageContext,
      primary: 'Айзек Азимов',
      secondary: [
        'Нельзя сказать человеку: «Ты можешь творить.',
        'Так давай, твори». Гораздо вернее подождать, пока он',
        'сам не скажет: «Я могу творить, и я буду творить, хотите',
        'вы этого или нет».'
      ]
    };
  },
  methods: {
    debugEvent(event: unknown) {
      console.log(event);
    }
  }
});
</script>
