// demo/vue-demo/src/App.vue
<template>
  <h1>Vue with unified components</h1>
  <hr />
  <text-block ref="text" :primary="primary" :secondary="secondary" :dark="true" @cite="debugEvent">
    <cite>http://www.asimovonline.com</cite>
  </text-block>
  <primary-button @click="debugEvent">Click me</primary-button>
  <hr />
  <test-page />
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { TestPage, TextBlock, PrimaryButton } from '@demo/ui-kit';

export default defineComponent({
  name: 'App',
  components: {
    TestPage,
    TextBlock,
    PrimaryButton
  },
  mounted() {
    console.log(this.$refs.text);
  },
  data() {
    return {
      primary: 'Айзек Азимов',
      secondary: [
        'Нельзя сказать человеку: «Ты можешь творить.',
        'Так давай, твори». Гораздо вернее подождать, пока он',
        'сам не скажет: «Я могу творить, и я буду творить, хотите',
        'вы этого или нет».'
      ]
    };
  },
  methods: {
    debugEvent(event: unknown) {
      console.log(event);
    }
  }
});
</script>

// demo/preact-demo/src/App.tsx
import { PrimaryButton, TestPage, TextBlock } from '@demo/ui-kit';
import { useCallback } from 'preact/hooks';

export function App() {
  const primary = 'Айзек Азимов';
  const secondary = [
    'Нельзя сказать человеку: «Ты можешь творить.',
    'Так давай, твори». Гораздо вернее подождать, пока он',
    'сам не скажет: «Я могу творить, и я буду творить, хотите',
    'вы этого или нет».'
  ];

  const debugEvent = useCallback((_: unknown) => {
    console.log(_);
  }, []);

  return (
    <>
      <h1>PREACT with unified components</h1>
      <hr />
      <TextBlock primary={primary} secondary={secondary} dark onCite={debugEvent}>
        <cite>http://www.asimovonline.com</cite>
      </TextBlock>
      <PrimaryButton onClick={debugEvent}>Click me</PrimaryButton>
      <hr />
      <TestPage />
    </>
  );
}
